package com.fit.eledger.cloud.ws.ledger;

/**
 * Service implementation of {ELedgerCloud} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ELedgerCloud", targetNamespace = "http://ws.cloud.eledger.fit.com/ledger", wsdlLocation = "wsdl/com/fit/eledger/cloud/ws/ledger/ELedgerCloud/ELedgerCloud.wsdl")
public class ELedgerCloud extends javax.xml.ws.Service {

	private final static java.net.URL ELEDGERCLOUD_WSDL_LOCATION;
	static {
		java.net.URL url = null;
		try {
			java.net.URL tmpUrl = ELedgerCloud.class.getClassLoader().getResource("wsdl/com/fit/eledger/cloud/ws/ledger/ELedgerCloud/ELedgerCloud.wsdl");
			url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
		} catch (java.net.MalformedURLException e) {
			e.printStackTrace();
		}
		ELEDGERCLOUD_WSDL_LOCATION = url;
	}

	/**
	 * Default service constructor.
	 */
	public ELedgerCloud() throws java.net.MalformedURLException {
		super(ELEDGERCLOUD_WSDL_LOCATION, new javax.xml.namespace.QName("http://ws.cloud.eledger.fit.com/ledger", "ELedgerCloud"));
	}

	public ELedgerCloud(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/**
	 * Get method for webservice port [ELedgerCloudService].
	 */
	@javax.xml.ws.WebEndpoint(name = "ELedgerCloudService")
	public com.fit.eledger.cloud.ws.ledger.ELedgerCloudService getELedgerCloudService() {
		javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://ws.cloud.eledger.fit.com/ledger", "ELedgerCloudService");
		return (com.fit.eledger.cloud.ws.ledger.ELedgerCloudService) super.getPort(portName, com.fit.eledger.cloud.ws.ledger.ELedgerCloudService.class);
	}
}
